# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kona-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kona-common/proprietary//system/usr/idc/sec_e-pen.idc:system//system/usr/idc/sec_e-pen.idc \
    vendor/samsung/kona-common/proprietary//system/usr/keylayout/sec_e-pen.kl:system//system/usr/keylayout/sec_e-pen.kl \
    vendor/samsung/kona-common/proprietary//system/usr/keylayout/sec_touchscreen.kl:system//system/usr/keylayout/sec_touchscreen.kl
